engines:
  radon: 
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - python
      - javascript
  fixme:
    enabled: true
  pep8:
    enabled: true
  pylint:
    enabled: true
ratings:
  paths:
    - Application/**
