doc-warnings: yes
test-warnings: yes
strictness: veryhigh
autodetect: yes
max-line-length: 120
requirements:
    - requirements.txt
python-targets:
    - 3
pep8:
    full: true
    disable:
      - too-many-return-statements
      - too-many-instance-variables
      - too-few-public-methods
pylint:
    run: true
